c:\Users\singh\OneDrive\Documents\GitHub\DA6401_Assignment-01\test.py:32: RuntimeWarning: overflow encountered in exp
  return np.exp(Z) / np.sum(np.exp(Z))
c:\Users\singh\OneDrive\Documents\GitHub\DA6401_Assignment-01\test.py:32: RuntimeWarning: invalid value encountered in divide
  return np.exp(Z) / np.sum(np.exp(Z))
c:\Users\singh\OneDrive\Documents\GitHub\DA6401_Assignment-01\test.py:160: RuntimeWarning: divide by zero encountered in log
  CE = [-Y_true[i] * np.log(Y_pred[i]) for i in range(len(Y_pred))]
c:\Users\singh\OneDrive\Documents\GitHub\DA6401_Assignment-01\test.py:160: RuntimeWarning: invalid value encountered in multiply
  CE = [-Y_true[i] * np.log(Y_pred[i]) for i in range(len(Y_pred))]
Epoch: 0, Loss: nan, Training accuracy:0.10, Validation Accuracy: 0.10, Time: 84.84, Learning Rate: 1.000e-03
Epoch: 1, Loss: nan, Training accuracy:0.10, Validation Accuracy: 0.10, Time: 70.89, Learning Rate: 1.000e-03
[34m[1mwandb[0m: [33mWARNING[0m Fatal error while uploading data. Some run data will not be synced, but it will still be written to disk. Use `wandb sync` at the end of the run to try uploading.
Epoch: 2, Loss: nan, Training accuracy:0.10, Validation Accuracy: 0.10, Time: 73.35, Learning Rate: 1.000e-03
